config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :purchases
  end

  get 'about' => 'home_about#index'
  get 'location' => 'home_location#index'

  resources :homeleads
  resources :helpdesks
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_user, ActiveAdmin::Devise.config
  resources :blogs
  get 'tags/:tag', to: 'blogs#index', as: "tag"
  resources :dashboard

  get "benefits/redeem_log/:id" => "benefits#redeem_log"

  resources :contacts, only: [:create]

  resources :forums do
    resources :comments
  end

  resources :community

  resources :enquiries
  resources :home

  resources :after_signup

  resources :profiles
  root 'home#index'

  namespace :admins do
    resources :dashboard
  end

  namespace :admins do
    root 'report#index'
  end

  namespace :admins do
    resources :rooms, :plans, :payments, :events, :companies, :bookings, :users, :report,:statistic, :invoices, :settings,:banners,:profiles,:benefits, :abouts, :testimonials,:contacts, :generators
    resources :suborders, :path => "invoices"

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings, :only => [:index,:show, :create, :update]
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions" }
  devise_for :admins, controllers: { registrations: "admins/registrations" }
  resources :plans
  resources :payments
  resources :events
  resources :bookings
  resources :purchases
  resources :invoices
  resources :benefits

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @admins = Admin.all
  	@banners = Banner.all
  	@plans = Plan.all
  	@settings = Setting.all
    @events = Event.all
    @benefits = Benefit.all
    @abouts = About.all
    @testimonials =  Testimonial.all
    @contact = Contact.new
    @homelead = Homelead.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_domain.html.erb
<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
<script type="text/javascript">
  $(document).ready(function(){

    $("#myCarousel").carousel({interval:5000});
    $(".owl-carousel").owlCarousel({
      loop:true,
      Autoplay:true,
      autoWidth:true,
      dots:true,
      items:3,
      navigationText:["<strong><i class='fa fa-angle-left'></i></strong>","<strong><i class='fa fa-angle-right'></i></strong>"],
      navigation:true,
      responsiveClass:true,
      responsive:{
        0:{
          items:1
        },
        480:{
          items:2
        },
        600:{
          items:2

        },
        768:{
          items:3

        },
        1024:{
          items:3
        }
      }
    });

    $(".maps").on("click",function(){
      $(".maps iframe").css("pointer-events","auto");
    });
    $(".maps").on("mouseleave",function(){
      $(".maps iframe").css("pointer-events","none");
    });
  });
 AOS.init();
</script>
<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
<div class="container-full">
<div id="myCarousel" class="carousel slide c1" data-ride="carousel">
      <!-- Indicators -->
      <div class="carousel-inner" role="listbox">
        <% @banners.each do |banner| %>
        <div class="item">
           <%= image_tag banner.image.url(:original), :class => "img-responsive bimage img-banner" %>
          <div class="container">
            <div class="carousel-caption banner">
            <% @settings.each do |setting| %>
              <%= image_tag setting.logo.url(:medium), :class => "clogo"%>
              <% end %>

              <h1 class="font-white"><%= banner.title %></h1>
              <p><%= banner.description %></p>
              <a href="#plans" class="cta1" style="margin-right:10px;">Book Now</a>
              <a href="#contacts" class="cta2">Contact Us</a>
              <% if user_signed_in? %>
                <%= link_to "dashboard", dashboard_index_path, :class => "btn btn1 navbar-btn" %>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete , :class => "btn btn1 navbar-btn" %>
              <% else %>
                <%= link_to "Sign in", new_user_session_path, :class => "cta1" %>
              <% end %>


              </ul>
            </div>
          </div>
        </div>
       <% end %>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>

<!-- about section -->
<div class="container-full">
    <% @abouts.each do |about| %>
    <!--custom css for background -->
    <style>
      @media screen and (min-width: 900px){
        .abg{
          background-image: url('<%= about.logo.url %>');  background-size: 100%;min-height:608px;background-repeat: no-repeat;
        }
      }
    </style>
    <% end %>
  </div>
  <!-- end about -->

  <!-- plan section -->
<div class="container-fluid text-center" id="plans">
  <% if !current_space.nil? %>
    <div class="row">
      <div class="col-md-6 col-xs-12 bg-black">
        <h1 class="font-white"  data-aos="slide-right">Plans & Pricing</h1>
        <hr class="line"></hr>
        <p class="font-white" style="font-size:20px;margin-top:20px;" data-aos="slide-up">Located around business and creative area, Offering beautiful space and vibrant community of like minded folks</p>
      </div>

      <div class="col-md-6 col-xs-12">
        <div class="owl-carousel" data-aos="slide-up">
          <% @plans.reverse_each do |plan| %>
            <div class="item plan" >
              <%= image_tag plan.pimage.url if plan.pimage.file? %>
              <div class="plan-details">
                <h3 class="font-white"><%= plan.name %></h3>
                <p class="font-white" style="font-weight:700;"><% if plan.price.to_f > 1000000 %>
                  <%=  number_to_currency(plan.price.to_f / 1000000, :unit => "IDR", :precision => 0).to_s %> Mio/<%= options_for_period[plan.period-1][0] %>
                  <% elsif plan.price.to_f > 1000 %>
                  <%= number_to_currency(plan.price.to_f / 1000, :unit => "IDR", :precision => 0) %> K/<%= options_for_period[plan.period-1][0] %>
                  <% else %>
                  Enquiry
                  <% end %>
                </p>
              </div>
            <!-- condition for pricing button -->
            <% if plan.price.nil? %>
              <div class="cta-plan" id="enquiry">
                <p>Enquire</p>
              </div>
            <% else %>
            <%= link_to :controller => "purchases", :action => "new", :plan => plan.id do %>
              <div class="cta-plan">
                <p>Book now</p>
              </div>
            <% end %>
            <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
  <!-- end plan -->

<!-- start testimonial -->
<% if @testimonials.present? %>
<div class="container-full testimonial">
  <h1 class="text-center" data-aos="slide-down">Testimonials</h1>
  <hr class="line"></hr>
  <div id="myCarousel2" class="carousel slide c2" data-ride="carousel">
        <!-- Indicators -->
    <div class="carousel-inner" role="listbox">
      <% @testimonials.each do |testimonial| %>
        <div class="item">
          <div class="container testimonial-body">
          <%= image_tag testimonial.image.url(:original), :class => "img-circle img-responsive", :style => "height:200px; width:200px;" %>
            <div class="testimonial-inner" data-aos="slide-up">
              <i class="fa fa-quote-left fa-2x font-orange" style="opacity:0.5;"></i>
              <h4><%= testimonial.description %></h4>
              <p><%= testimonial.name %> - <%= testimonial.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<% end %>
<!-- end testimonial -->

<!-- start event -->

<!-- end event -->


<!-- start location -->
<% if current_space.setting.try(:google_maps).present? %>
  <div class="container-full text-center" style="min-height:500px;margin-bottom:3%">

    <div class="row">
      <div class="col-md-6 col-xs-12 bg-black"  data-aos="slide-right">
        <h2 class="font-white">Contact</h2>
        <hr class="line"></hr>
        <% @settings.each do |setting|%>
        <div class="address">
          <p><i class="fa fa-map-marker font-orange"></i> <%= setting.address.html_safe%></p>
        </div>
        <% end %>
        <ul class="list-inline">
          <li><a href="https://www.facebook.com/evhive.co/" target="_blank"><i class="fa fa-facebook fa-lg"></i></a></li>
          <li><a href="https://www.linkedin.com/company-beta/13178803/?pathWildcard=13178803" target="_blank"><i class="fa fa-linkedin fa-lg"></i></a></li>
          <li><a href="https://www.instagram.com/evhive/?hl=en" target="_blank"><i class="fa fa-instagram fa-lg"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12 maps" data-aos="slide-up">
        <iframe
          width="100%"
          height="468"
          frameborder="0"
          src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBE6HrvPniuUQFUj5OzOibQoHWYce3AQ3k&q=<%= current_space.setting.google_maps %>" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
<% end %>
<!-- end location -->

<!-- start footer -->
<!-- <footer class="text-muted well" id="last-footer">
  <% @settings.each do |setting| %>
    <section>
      <div class="row" style="font-size:11px;">
        <div class="container">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-3">
                <div class="row footlinks">
                  <div class="col-xs-12">
                    <h2>Location</h2>
                    <div class="haddress"><%= setting.address.html_safe %></div>
                  </div>
                </div>
              </div>
              <div class="col-md-3"></div>
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="row footlinks">
                  <div class="col-xs-12">
                    <%= image_tag setting.logo.url(:medium) %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</footer> -->
<!-- end footer -->
<!-- start contact -->
<div class="container-full">
  <div class="container m2" id="contacts" style="min-height:300px;margin-top:5%;margin-bottom:5%" data-aos="slide-right">
    <div class="col-lg-12">
      <h2 class="text-center">Send <span class="font-orange">Us</span> A Message</h2>
      <br>
      <p class="text-center"><%= current_space.setting.about.html_safe if current_space.setting.try(:about).present? %></p>
      <%= render 'contacts/form' %>
    </div>
  </div>
</div>
<!-- end contact -->
<!-- modal popup -->
<div class="modal fade" id="modals" role="dialog">
  <div class="modal-dialog" role="document">
      <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Enquiry form</h4>
      </div>
      <div class="modal-body">
        <p><%= render 'contacts/form' %></p>
      </div>
      <div class="modal-footer">
        <p>Please fill your enquiry at the given form</p>
      </div>
    </div>
  </div>
</div>
<!-- end modal -->

app/views/home/_event.html.erb
<div class="container mc">
  <div class="col-lg-12 m2" style="margin-bottom:25px">
    <div class="centered" >
      <p class="s28">We know what you need</p>
      <p class="intro_text">As a believer of peer-to-peer learning, we organize various sharing, keynotes, panels and workshops with experts in the industry every week. Through events and workshops by our network of entrepreneurs and tech communities, we help local startups grow their businesses. </p>
    </div>
  </div>
  <% @events.last(3).each do |event| %>
    <div class="col-md-4 col-xs-12" data-aos="zoom-in">
      <div class="card home-event">
        <%= image_tag event.image.url(:medium), :class => "img-responsive"%>
        <div class="card-block">
          <h4><%= event.name %></h4>
          <!-- <p class="event-desc"><%= truncate(event.description.html_safe, :length => 100 ) %></p> -->
          <p><%= event.start_date.try(:strftime, "%d %B %Y") %> @ <%= event.start_date.try(:strftime, "%I:%M %p") %></p>
          <p><%= link_to "View Event", event_path(event), :class => "btn-view"%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% if current_space.nil? %>
<%= render 'home/landing' %>
<% end %>
<!-- start the if subdomain exist -->
<% if !current_space.nil? %>
<%= render 'home/domain' %>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
  $('#myCarousel').find('.item').first().addClass('active');
  $('#myCarousel2').find('.item').first().addClass('active');

});
$("#book").click(function() {
    $('html,body').animate({
        scrollTop: $("#contacts").offset().top -100 },
        'slow');
});
$("#enquiry").click(function() {
    $('html,body').animate({
        scrollTop: $("#contacts").offset().top -100 },
        'slow');
});
</script>