config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :purchases
  end

  get 'about' => 'home_about#index'
  get 'location' => 'home_location#index'

  resources :homeleads
  resources :helpdesks
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_user, ActiveAdmin::Devise.config
  resources :blogs
  get 'tags/:tag', to: 'blogs#index', as: "tag"
  resources :dashboard

  get "benefits/redeem_log/:id" => "benefits#redeem_log"

  resources :contacts, only: [:create]

  resources :forums do
    resources :comments
  end

  resources :community

  resources :enquiries
  resources :home

  resources :after_signup

  resources :profiles
  root 'home#index'

  namespace :admins do
    resources :dashboard
  end

  namespace :admins do
    root 'report#index'
  end

  namespace :admins do
    resources :rooms, :plans, :payments, :events, :companies, :bookings, :users, :report,:statistic, :invoices, :settings,:banners,:profiles,:benefits, :abouts, :testimonials,:contacts, :generators
    resources :suborders, :path => "invoices"

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings, :only => [:index,:show, :create, :update]
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions" }
  devise_for :admins, controllers: { registrations: "admins/registrations" }
  resources :plans
  resources :payments
  resources :events
  resources :bookings
  resources :purchases
  resources :invoices
  resources :benefits

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  default_scope {where(admin_id: Admin.current_id) if Admin.current_id}
  belongs_to :admin
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ContactsController
  layout 'admin'
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end
  #
  # # GET /contacts/1
  # # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to [:admins,@contact], notice: 'enquiry has been submitted' }
        format.json { render :show, status: :created, location: [:admins,@contact] }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to [:admins,@contact], notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admins,@contact] }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to admins_contacts_path, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstname, :lastname, :phone, :email, :enquiry)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if verify_recaptcha(model: @contact) && @contact.save
        UserMailer.contact_facility(@contact).deliver_now
        format.html { redirect_to root_path, notice: 'enquiry has been submitted' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstname, :lastname, :phone, :email, :enquiry)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/contacts/_form.html.erb
<%= form_for([:admins,@contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="col-md-12"> -->


  <div class="form-group col-md-6">
    <%= f.label 'First name', :class => 'control-label' %><br>
    <%= f.text_field :firstname, :class => 'form-control', :placeholder => 'First name' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label 'Last name', :class => 'control-label' %>
    <%= f.text_field :lastname, :class => 'form-control', :placeholder => 'Last name'  %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :phone, :class => 'control-label' %><br>
    <%= f.text_field :phone, :class => 'form-control', :placeholder => 'Phone Number'  %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :email, :class => 'control-label' %><br>
    <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email'  %>
  </div>
  <div class="form-group col-md-12">
    <%= f.label :enquiry %><br>
    <%= f.text_area :enquiry, :class => 'form-control col-lg-12', :placeholder => 'Enquiry'  %>
  </div>
  <div class="form-group col-md-12">
    <%= f.submit 'Submit',  :class => 'btn btn-success'  %>
  </div>

<!-- </div> -->
<% end %>

app/views/admins/contacts/edit.html.erb
<div class="box-header with-border">
  <h3 class="box-title">Edits</h3>
</div>
<%= render 'form' %>

<%= link_to 'Show', [:admins,@contact] %> |
<%= link_to 'Back', admins_contacts_path %>

app/views/admins/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="box-header with-border">
  <h3 class="box-title">List Contacts Lead</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Created at:</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Enquiry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.firstname %> <%= contact.lastname %></td>
        <td><%= contact.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.enquiry %></td>
        <td><%= link_to 'Show', admins_contact_path(contact), :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admins_contact_path(contact), :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', admins_contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_admins_contact_path %>

app/views/admins/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_contacts_path %>

app/views/admins/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Enquiry:</strong>
  <%= @contact.enquiry %>
</p>

<%= link_to 'Edit', edit_admins_contact_path(@contact) %> |
<%= link_to 'Back', admins_contacts_path %>