config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :purchases
  end

  get 'about' => 'home_about#index'
  get 'location' => 'home_location#index'

  resources :homeleads
  resources :helpdesks
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_user, ActiveAdmin::Devise.config
  resources :blogs
  get 'tags/:tag', to: 'blogs#index', as: "tag"
  resources :dashboard

  get "benefits/redeem_log/:id" => "benefits#redeem_log"

  resources :contacts, only: [:create]

  resources :forums do
    resources :comments
  end

  resources :community

  resources :enquiries
  resources :home

  resources :after_signup

  resources :profiles
  root 'home#index'

  namespace :admins do
    resources :dashboard
  end

  namespace :admins do
    root 'report#index'
  end

  namespace :admins do
    resources :rooms, :plans, :payments, :events, :companies, :bookings, :users, :report,:statistic, :invoices, :settings,:banners,:profiles,:benefits, :abouts, :testimonials,:contacts, :generators
    resources :suborders, :path => "invoices"

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings, :only => [:index,:show, :create, :update]
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions" }
  devise_for :admins, controllers: { registrations: "admins/registrations" }
  resources :plans
  resources :payments
  resources :events
  resources :bookings
  resources :purchases
  resources :invoices
  resources :benefits

end

app/models/generator.rb
class Generator < ActiveRecord::Base
    default_scope {where(admin_id: Admin.current_id) if Admin.current_id}
    has_many :suborders

    def search_suborders
      suborders = Suborder.all
      suborders = Suborder.select('sum(suborders.total/plans.price/plans.deposit) as myval, plans.name as plan_name').group('plans.name').joins('left join purchases on suborders.purchase_id = purchases.id').joins('left join plans on purchases.plan_id = plans.id').where('suborders.start_date between ? and ? and plans.name = ? ' ,  start_date.beginning_of_month, start_date.end_of_month, plan_name)

      return suborders
    end
end

app/controllers/admins/generators_controller.rb
class Admins::GeneratorsController < ApplicationController
  layout 'admin'
  def index
    @generators = Generator.all.order(id: :desc)
  end
  def new
    @generator = Generator.new
    @plans = Plan.uniq.pluck(:name)
  end

  def create
    @generator = Generator.create(gerenator_params)
    redirect_to [:admins,@generator]
  end

  def show
    @generator = Generator.find(params[:id])
  end

  private

  def gerenator_params
    params.require(:generator).permit(:plan_name,:start_date,:end_date)
  end
end

app/helpers/admins/generators_helper.rb
module Admins::GeneratorsHelper
end

app/views/admins/generators/index.html.erb
<div class="col-md-12">
  <p>Monthly occupancy generator</p>
  <%= link_to 'Generate occupancy rate', new_admins_generator_path, :class => 'btn btn-default btn-success' %>
<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>plan name</th>
      <th>Month</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>
  <tbody>
    <% @generators.each do |generator| %>
      <tr>
        <td><%= link_to generator.id , admins_generator_path(generator) %></td>
        <td><%= generator.plan_name %></td>
        <td><%= generator.start_date.strftime("%B") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admins/generators/new.html.erb
<p>Company Invoice Generator</p>
<br>
<%= form_for [:admins,@generator], html: {class: "pure-form"} do |f| %>
  <div class="form-group">
    <%= f.label :plan_name %>
    <%= f.select :plan_name, options_for_select(@plans), :include_blank => true, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Generate", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admins/generators/show.html.erb
<div class="col-md-12">
<p><%= @generator.start_date.strftime("%B") %></p>
 <% @generator.search_suborders.each do |f| %>
  <p><%= f.plan_name %></p>
  <p>Occupancy: <%= f.myval * 100 %> %</p>
  <%  end  %>
</div>