config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :purchases
  end

  get 'about' => 'home_about#index'
  get 'location' => 'home_location#index'

  resources :homeleads
  resources :helpdesks
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_user, ActiveAdmin::Devise.config
  resources :blogs
  get 'tags/:tag', to: 'blogs#index', as: "tag"
  resources :dashboard

  get "benefits/redeem_log/:id" => "benefits#redeem_log"

  resources :contacts, only: [:create]

  resources :forums do
    resources :comments
  end

  resources :community

  resources :enquiries
  resources :home

  resources :after_signup

  resources :profiles
  root 'home#index'

  namespace :admins do
    resources :dashboard
  end

  namespace :admins do
    root 'report#index'
  end

  namespace :admins do
    resources :rooms, :plans, :payments, :events, :companies, :bookings, :users, :report,:statistic, :invoices, :settings,:banners,:profiles,:benefits, :abouts, :testimonials,:contacts, :generators
    resources :suborders, :path => "invoices"

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings, :only => [:index,:show, :create, :update]
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions" }
  devise_for :admins, controllers: { registrations: "admins/registrations" }
  resources :plans
  resources :payments
  resources :events
  resources :bookings
  resources :purchases
  resources :invoices
  resources :benefits

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  default_scope {where(admin_id: Admin.current_id) if Admin.current_id}

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" },    :path => ":rails_root/public/images/admin/:class/:attachment/:id/:style/:filename",:url => "/images/admin/:class/:attachment/:id/:style/:filename"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },    :path => ":rails_root/public/images/admin/:class/:attachment/:id/:style/:filename",:url => "/images/admin/:class/:attachment/:id/:style/:filename"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/admins/testimonials_controller.rb
class Admins::TestimonialsController < TestimonialsController
  layout 'admin'

  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to [:admins,@testimonial], notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admins,@testimonial] }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to [:admins,@testimonial], notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: [:admins,@testimonial] }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to admins_testimonials_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :title, :description,:logo,:image)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.name %></td>
        <td><%= testimonial.title %></td>
        <td><%= testimonial.description %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @testimonial.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @testimonial.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @testimonial.description %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>